language: node_js
node_js:
  - stable
cache: yarn
script:
  - yarn
  - yarn build
  - yarn test:single
notifications:
  slack:
    secure: iUlxj4R1Mf3ZHuaHiznrVAQIQdzZmW3sCV7+wtWaR3sSd+Trx6jS/sTXKVWW8GPM4DoGDMrkleZodwWiKmZvP/lfIIULPQiGJF8edQhh3ux4/w4dRM4bF2da4CeBiGSMbccmT8ydfpN7RfyYzGzBgLeX4GIC8YuCFtowz4B6TtnBRBTAW58yrD+MyiP5T0bh+A2ov2qutW8KcaE/MHllo5J4rv2Vz4wspG3qgSpckMAGwLTuSPzrPjNy5SMWXnXjkzW8dVx4fYnQ/u6S9/BMgMio2cn2P1LyV+EvwQ8hbre3L2gD7tkGOVhh7NL7fAs03JXDlFkb8VaUG+MRdTQYHM7llfFZkpW2pNF1SCynSvTLQO4BPNlmvWlrXDzzk9oBivxRGNspac8fSH3uZvMeeiArC27lsRquMOnQA17tfoutlXRtRxzZPBcPMHSxCJ2Y/nKjXE/9pnoGheVD7olfGK4lUIz3mZo7mtsDbzLn2V/8ejg9BU4EToGWtmEyjwsrZdeuKBFprV5TnBWt3t1/O8aw2+lezrzri8eEYbmLPcDvXL/RQISoQd6nLAUCoXMn/SWOD/aOhEdBEyy7FcQ4KqiDu+kEwwAyDRlm1kdtIYJdwnGloSBx7RVoVbsWIDa5FTZu/FtRL46egjjH2s6VYr01YUtCt90Q+4QYumfE+XQ=
