service:
  name: serverless-microservice-template

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    accountId: '#{AWS::AccountId}'
    region: '#{AWS::Region}'
    stage: ${self:provider.stage}

functions:
  ping:
    handler: src/handlers/ping/ping.default
    events:
      - http:
          method: get
          path: ping

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'yarn'
    excludeFiles: src/**/*.test.ts
