service:
  name: serverless-microservice-template

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-plugin-aws-alerts

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    ACCOUNT_ID: '#{AWS::AccountId}'
    REGION: '#{AWS::Region}'
    STAGE: ${self:provider.stage}

functions:
  ping:
    handler: src/handlers/ping/ping.default
    events:
      - http:
          method: get
          path: ping

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'yarn'
    excludeFiles: src/**/*.test.ts
  alerts:
    stages:
      - test
      - prod
    topics:
      ok:
        topic: ${opt:stage}-${self:service}-alerts-ok
        notifications:
          - protocol: email
            endpoint: devops@egonoid.com
      alarm:
        topic: ${opt:stage}-${self:service}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: devops@egonoid.com
    nameTemplate: $[functionId]-$[metricName]
    alarms:
      - functionErrors
    definitions:
      functionErrors:
        treatMissingData: notBreaching
